[
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#doel",
    "label": [
      {
        "@language": "nl",
        "@value": "doel"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#consument",
    "label": [
      {
        "@language": "nl",
        "@value": "consument"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#aanbieder",
    "label": [
      {
        "@language": "nl",
        "@value": "aanbieder"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#deelname",
    "label": [
      {
        "@language": "nl",
        "@value": "deelname"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#criteriumvereiste",
    "label": [
      {
        "@language": "nl",
        "@value": "criteriumvereiste"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijs",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijs"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloning",
    "label": [
      {
        "@language": "nl",
        "@value": "beloning"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloningtype",
    "label": [
      {
        "@language": "nl",
        "@value": "beloningtype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijstype",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijstype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#isgerelateerdmet",
    "label": [
      {
        "@language": "nl",
        "@value": "isGerelateerdMet"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#sponsor",
    "label": [
      {
        "@language": "nl",
        "@value": "sponsor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "huisnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "busnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#gemeentenaam",
    "label": [
      {
        "@language": "nl",
        "@value": "gemeentenaam"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#land",
    "label": [
      {
        "@language": "nl",
        "@value": "land"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/cultureel-erfgoed#tekst",
    "label": [
      {
        "@language": "nl",
        "@value": "tekst"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#volledigeNaam",
    "label": [
      {
        "@language": "nl",
        "@value": "volledige naam"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#/Sterfdatum",
    "label": [
      {
        "@language": "nl",
        "@value": "sterfdatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#/Geboortedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "geboortedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/cultureel-erfgoed#type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#doel",
    "label": [
      {
        "@language": "nl",
        "@value": "doel"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#consument",
    "label": [
      {
        "@language": "nl",
        "@value": "consument"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#aanbieder",
    "label": [
      {
        "@language": "nl",
        "@value": "aanbieder"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#deelname",
    "label": [
      {
        "@language": "nl",
        "@value": "deelname"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#criteriumvereiste",
    "label": [
      {
        "@language": "nl",
        "@value": "criteriumvereiste"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijs",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijs"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloning",
    "label": [
      {
        "@language": "nl",
        "@value": "beloning"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloningtype",
    "label": [
      {
        "@language": "nl",
        "@value": "beloningtype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijstype",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijstype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#isgerelateerdmet",
    "label": [
      {
        "@language": "nl",
        "@value": "isGerelateerdMet"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#sponsor",
    "label": [
      {
        "@language": "nl",
        "@value": "sponsor"
      }
    ]
  }
]
