[
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#looptijd",
    "label": [
      {
        "@language": "nl",
        "@value": "looptijd"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#aantalBeschikbareLoketuren",
    "label": [
      {
        "@language": "nl",
        "@value": "aantal beschikbare loketuren"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#uitbetalingStart",
    "label": [
      {
        "@language": "nl",
        "@value": "uitbetalingStart"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#bouwjaar",
    "label": [
      {
        "@language": "nl",
        "@value": "bouwjaar"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#laatsteRenovatie",
    "label": [
      {
        "@language": "nl",
        "@value": "laatste renovatie"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "huisnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "busnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#gemeentenaam",
    "label": [
      {
        "@language": "nl",
        "@value": "gemeentenaam"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#land",
    "label": [
      {
        "@language": "nl",
        "@value": "land"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#tijdstip",
    "label": [
      {
        "@language": "nl",
        "@value": "tijdstip"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Gebouw.kenmerk",
    "label": [
      {
        "@language": "nl",
        "@value": "kenmerk"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Gebouweenheid.kenmerk",
    "label": [
      {
        "@language": "nl",
        "@value": "kenmerk"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#verstrektDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "verstrektDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#thema",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Adviesverlening.type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Begeleiding.type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#categorieWerken",
    "label": [
      {
        "@language": "nl",
        "@value": "categorieWerken"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Financiering.type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#verstrektAan",
    "label": [
      {
        "@language": "nl",
        "@value": "verstrektAan"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#GeregistreerdContact.onderwerp",
    "label": [
      {
        "@language": "nl",
        "@value": "onderwerp"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#gefinancierdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "gefinancierdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#rentevoet",
    "label": [
      {
        "@language": "nl",
        "@value": "rentevoet"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#begeleider",
    "label": [
      {
        "@language": "nl",
        "@value": "begeleider"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#bedrag",
    "label": [
      {
        "@language": "nl",
        "@value": "bedrag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#locatie",
    "label": [
      {
        "@language": "nl",
        "@value": "locatie"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#renovatiebegeleider",
    "label": [
      {
        "@language": "nl",
        "@value": "renovatiebegeleider"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#adviesverlener",
    "label": [
      {
        "@language": "nl",
        "@value": "adviesverlener"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#energiescanner",
    "label": [
      {
        "@language": "nl",
        "@value": "energiescanner"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#output",
    "label": [
      {
        "@language": "nl",
        "@value": "output"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Basistaak.type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#Gebouw.adres",
    "label": [
      {
        "@language": "nl",
        "@value": "adres"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#Gebouw.status",
    "label": [
      {
        "@language": "nl",
        "@value": "status"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#Gebouweenheid.adres",
    "label": [
      {
        "@language": "nl",
        "@value": "adres"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#functie",
    "label": [
      {
        "@language": "nl",
        "@value": "functie"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#Gebouweenheid.status",
    "label": [
      {
        "@language": "nl",
        "@value": "status"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Begeleiding.fase",
    "label": [
      {
        "@language": "nl",
        "@value": "fase"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Project.fase",
    "label": [
      {
        "@language": "nl",
        "@value": "fase"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#Contact.onderwerp",
    "label": [
      {
        "@language": "nl",
        "@value": "onderwerp"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#financiering",
    "label": [
      {
        "@language": "nl",
        "@value": "financiering"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/dienst#heeftParticipant",
    "label": [
      {
        "@language": "nl",
        "@value": "heeftParticipant"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/dienst#Participatie.publiekeDienstverlening",
    "label": [
      {
        "@value": "Participatie.PubliekeDienstverlening"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/dienst#Participatie.agent",
    "label": [
      {
        "@value": "Participatie.Agent"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#verricht",
    "label": [
      {
        "@language": "nl",
        "@value": "verricht"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#gerenoveerdGebouw",
    "label": [
      {
        "@language": "nl",
        "@value": "gerenoveerdGebouw"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/energiehuis#gerenoveerdeGebouweenheid",
    "label": [
      {
        "@language": "nl",
        "@value": "gerenoveerdeGebouweenheid"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/gebouw#bestaatUit",
    "label": [
      {
        "@language": "nl",
        "@value": "bestaatUit"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#verwijstNaar",
    "label": [
      {
        "@language": "nl",
        "@value": "verwijst naar"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#doel",
    "label": [
      {
        "@language": "nl",
        "@value": "doel"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#consument",
    "label": [
      {
        "@language": "nl",
        "@value": "consument"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#aanbieder",
    "label": [
      {
        "@language": "nl",
        "@value": "aanbieder"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#deelname",
    "label": [
      {
        "@language": "nl",
        "@value": "deelname"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#criteriumvereiste",
    "label": [
      {
        "@language": "nl",
        "@value": "criteriumvereiste"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijs",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijs"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloning",
    "label": [
      {
        "@language": "nl",
        "@value": "beloning"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloningtype",
    "label": [
      {
        "@language": "nl",
        "@value": "beloningtype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijstype",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijstype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#isgerelateerdmet",
    "label": [
      {
        "@language": "nl",
        "@value": "isGerelateerdMet"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#sponsor",
    "label": [
      {
        "@language": "nl",
        "@value": "sponsor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "huisnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer",
    "label": [
      {
        "@language": "nl",
        "@value": "busnummer"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#gemeentenaam",
    "label": [
      {
        "@language": "nl",
        "@value": "gemeentenaam"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#land",
    "label": [
      {
        "@language": "nl",
        "@value": "land"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/cultureel-erfgoed#tekst",
    "label": [
      {
        "@language": "nl",
        "@value": "tekst"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#volledigeNaam",
    "label": [
      {
        "@language": "nl",
        "@value": "volledige naam"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#/Sterfdatum",
    "label": [
      {
        "@language": "nl",
        "@value": "sterfdatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#/Geboortedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "geboortedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/cultureel-erfgoed#type",
    "label": [
      {
        "@language": "nl",
        "@value": "type"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/adres#verwijstNaar",
    "label": [
      {
        "@language": "nl",
        "@value": "verwijst naar"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#heeftRelatieMet",
    "label": [
      {
        "@language": "nl",
        "@value": "heeft relatie met"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#Persoonsrelatie.persoon.source",
    "label": [
      {
        "@value": "Persoon (source)"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/persoon#Persoonsrelatie.persoon.target",
    "label": [
      {
        "@value": "Persoon (target)"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/cultureel-erfgoed#Rol.activiteit",
    "label": [
      {
        "@value": "Rol.Activiteit"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#doel",
    "label": [
      {
        "@language": "nl",
        "@value": "doel"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#consument",
    "label": [
      {
        "@language": "nl",
        "@value": "consument"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#aanbieder",
    "label": [
      {
        "@language": "nl",
        "@value": "aanbieder"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#deelname",
    "label": [
      {
        "@language": "nl",
        "@value": "deelname"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#criteriumvereiste",
    "label": [
      {
        "@language": "nl",
        "@value": "criteriumvereiste"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijs",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijs"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloning",
    "label": [
      {
        "@language": "nl",
        "@value": "beloning"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#beloningtype",
    "label": [
      {
        "@language": "nl",
        "@value": "beloningtype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#bewijstype",
    "label": [
      {
        "@language": "nl",
        "@value": "bewijstype"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#isgerelateerdmet",
    "label": [
      {
        "@language": "nl",
        "@value": "isGerelateerdMet"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/incentiveringsplatform#sponsor",
    "label": [
      {
        "@language": "nl",
        "@value": "sponsor"
      }
    ]
  }
]
