[
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#opnamedatum",
    "label": [
      {
        "@language": "nl",
        "@value": "opnamedatum"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "fractiemetingwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpunt",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpunt"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeksresultaat.meetreekswaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetreekswaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntOndergrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntOndergrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetpuntBovengrens",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntBovengrens"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreekswaarde.meetwaarde",
    "label": [
      {
        "@language": "nl",
        "@value": "meetwaarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Meetreeks.meetpuntparameter",
    "label": [
      {
        "@language": "nl",
        "@value": "meetpuntparameter"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Geometrie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.methode",
    "label": [
      {
        "@language": "nl",
        "@value": "methode"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#Opmeting.uitgevoerdDoor",
    "label": [
      {
        "@language": "nl",
        "@value": "uitgevoerdDoor"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/generiek#DirectePositie.opmeting",
    "label": [
      {
        "@language": "nl",
        "@value": "opmeting"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.ligging",
    "label": [
      {
        "@language": "nl",
        "@value": "ligging"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.maaiveld",
    "label": [
      {
        "@language": "nl",
        "@value": "maaiveld"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_RuimtelijkBemonsteringsobject.diepte",
    "label": [
      {
        "@language": "nl",
        "@value": "diepte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Maaiveld.hoogte",
    "label": [
      {
        "@language": "nl",
        "@value": "hoogte"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#BO_Curvewaardepaar.laag",
    "label": [
      {
        "@language": "nl",
        "@value": "laag"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#Laag.waarde",
    "label": [
      {
        "@language": "nl",
        "@value": "waarde"
      }
    ]
  },
  {
    "assignedURI": "https://data.vlaanderen.be/ns/bodem-en-ondergrond#aanvangspeil",
    "label": [
      {
        "@language": "nl",
        "@value": "aanvangspeil"
      }
    ]
  }
]
